#!/usr/bin/env python3
"""Build a conservative MACTree mechanism profile from standalone sources.

This does not enable MACTree timing in the simulator.  It extracts the structural
parameters needed before any timing claim is allowed.
"""
from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path
from typing import Any


PARAMETERS = [
    "rowSize",
    "colSize",
    "dataWidth",
    "outputWidth",
    "pipeline",
    "tLatency",
    "compressionFactor",
    "add_skip_en",
    "tileSize",
    "maxKernelBlockCout",
    "maxKernelBlockCin",
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def extract_config(path: Path) -> dict[str, str]:
    text = read_text(path)
    values: dict[str, str] = {}
    for name in PARAMETERS:
        match = re.search(rf"\bval\s+{re.escape(name)}\s*=\s*([^\n/]+)", text)
        if match:
            values[name] = match.group(1).strip().rstrip(",")
        else:
            values[name] = "MISSING"
    return values


def count_occurrences(path: Path, patterns: list[str]) -> dict[str, int]:
    text = read_text(path)
    return {pattern: len(re.findall(pattern, text)) for pattern in patterns}


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def build_rows(base_root: Path, mactree_root: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    base_config = base_root / "src" / "main" / "scala" / "core" / "Config.scala"
    mactree_config = mactree_root / "src" / "main" / "scala" / "core" / "Config.scala"
    base_cim = base_root / "src" / "main" / "scala" / "core" / "CIMcore.scala"
    mactree_cim = mactree_root / "src" / "main" / "scala" / "core" / "CIMcore.scala"

    base = extract_config(base_config)
    mactree = extract_config(mactree_config)
    rows: list[dict[str, Any]] = []
    for parameter in PARAMETERS:
        rows.append(
            {
                "parameter": parameter,
                "base_value": base.get(parameter, "MISSING"),
                "mactree_value": mactree.get(parameter, "MISSING"),
                "changed": base.get(parameter, "MISSING") != mactree.get(parameter, "MISSING"),
                "source_base": str(base_config),
                "source_mactree": str(mactree_config),
            }
        )

    patterns = [
        r"class\s+MACTree\b",
        r"class\s+MACTreeFlood\b",
        r"class\s+MACTreeRefine\b",
        r"add_skip_en",
        r"wZero\s*\|\|\s*aZero",
        r"stageRegistersOut",
    ]
    base_counts = count_occurrences(base_cim, patterns)
    mactree_counts = count_occurrences(mactree_cim, patterns)
    evidence_rows = [
        {
            "pattern": pattern,
            "base_count": base_counts[pattern],
            "mactree_count": mactree_counts[pattern],
            "changed": base_counts[pattern] != mactree_counts[pattern],
            "source_base": str(base_cim),
            "source_mactree": str(mactree_cim),
        }
        for pattern in patterns
    ]
    return rows, evidence_rows


def write_readme(out_dir: Path) -> None:
    lines = [
        "# MACTree mechanism profile",
        "",
        "This directory is generated by `flood_local/build_mactree_profile.py`.",
        "",
        "## Purpose",
        "",
        "It extracts structural differences between the base FLOOD tree and the standalone `mactree/` material.",
        "It does not enable mactree timing in the simulator.",
        "",
        "## Strict paper policy",
        "",
        "- This profile is evidence inventory only.",
        "- No latency or speedup row may use MACTree effects until timing and value checks pass.",
        "- Required evidence: RTL/testbench cycles, output values, and activity counters if power is claimed.",
        "",
    ]
    out_dir.joinpath("README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-root", default="FLOOD")
    parser.add_argument("--mactree-root", default="mactree/flood")
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    profile_rows, evidence_rows = build_rows(Path(args.base_root), Path(args.mactree_root))
    write_csv(out_dir / "mactree_config_profile.csv", profile_rows)
    write_csv(out_dir / "mactree_source_evidence.csv", evidence_rows)
    write_csv(
        out_dir / "mactree_paper_gate.csv",
        [
            {
                "mechanism": "mactree",
                "simulator_status": "profile_only_not_enabled",
                "confidence_grade": "D_mactree_timing_not_validated",
                "paper_use_policy": "exclude_from_main_performance_tables",
                "required_to_enable": "direct RTL/testbench timing cycles plus output-value pass; activity counters required for power claims",
            }
        ],
    )
    write_readme(out_dir)
    print(f"wrote MACTree profile to {out_dir}")


if __name__ == "__main__":
    main()
